let geography_notes=
[{ title: "Geography notes Rivers ",content:`<input id="chapter" placeholder="Chapter" value="Geography notes">
            <input id="subtitle" class="subtitle" placeholder="Chapter Name" value="Rivers">
            <div id="editor" class="editor" contenteditable="true" style="background-size: 100% 32px;">
                <article><br></article><article><br></article><article>Sources of Rivers joining Ganga</article><article><ol><li><b>YAMUNA&nbsp;</b>&gt; Bandarpunch</li><li><b>BHAGIRATHI&nbsp;</b>&gt; Gangotri glacier &gt; Gaumukh (UK)</li><li><b>MANDAKINI&nbsp;</b>&gt; Kedarnath</li><li><b>ALAKNANDA&nbsp;</b>&gt; Satopanth glacier &gt; Badrinath</li><li><span style="background-color: initial; caret-color: red;"><b>RAMGANGA&nbsp;</b>&gt; Garhwal hills, Gairsain UK</span></li><li><b>GOMTI&nbsp;</b>&gt; Gomat Taal (Fulhaar jheel) near Madho Tanda, Pilibhit, UK</li><li><b>GHAGHARA&nbsp;</b>&gt; Mapchachungo glacier &gt; tributery (tila, seti, beri,kali or sharda)</li><li><b>GANDAK&nbsp;</b>&gt; Nepal&nbsp; between Dhaulagiri and Everest</li><li><b>SARDA&nbsp;</b>or&nbsp;<b>SARYU&nbsp;</b>&gt; Milam glacier, Nepal (Goriganga) &gt; name in nepal&nbsp;<b>KALI</b>&gt;&nbsp;</li><li><b>KOSI&nbsp;</b>&gt; north of Everest, tibet &gt; tributery&gt; arun, son(west), tamur(east)</li><li><b>MAHANANDA&nbsp;</b>&gt; Darjiling hills</li><li><b>DAMODAR&nbsp;</b>&gt; East of Chotanagpur plateau &gt; rift vally &gt; joins hugli</li><li><b>SON&nbsp;</b>&gt; Amarkantak plateau</li><li><b>CHAMBAL&nbsp;</b>&gt; Mhow, Malwa plateau, MP<br></li></ol><br></article><article><br></article><article><br></article><article><br></article><article><br></article><article><br></article><article><br></article><article><br></article><article><br></article><article><br></article><article><br></article><article><br></article><article><br></article><article>Type Here</article>
            </div>`}



            ,{ title: "Geography notes Landforms ",content:`<input id="chapter" placeholder="Chapter" value="Geography notes">
            <input id="subtitle" class="subtitle" placeholder="Chapter Name" value="Landforms">
            <div id="editor" class="editor" contenteditable="true" style="background-size: 100% 32px;">
                <article><br></article><article>Landforms</article><article>@ Running water</article><article><b>EROSIONAL FEATURES</b><br><ol><li>Vallyes</li><li>Potholes and Plunge Pools</li><li>Meandering &gt; Incised and Entrinched (different from meandering which is depositional feature)</li><li>River Terraces</li></ol><div><br></div><div><b>Depositional FEATURES</b><ol><li>alluvial fans</li><li>deltas</li><li>flood plains &gt; leeves &gt; point bars</li><li>Meandering</li><li>braided channels</li></ol><div><br></div><div><br></div><div>@ Ground Water</div><div><b>EROSIONAL FEATURES</b><ol><li><b>Swallow holes</b> &gt; small depressions</li><li><b>Sink holes</b> &gt; funnel shape</li><li><b>Doline</b> &gt; Collapsed sinks</li><li><b>Uvalas</b> &gt; valley of sink holes</li><li><b>Caves</b> &gt; mainly limestone, shales, dolomites, sandstone | quartzite</li></ol><div><br></div><div><b>DEPOSITIONAL FEATURES</b><ol><li>satalcites</li><li>stalgmites</li><li>pillars</li></ol></div></div><div><br></div><div><br></div><div>@ Glaciers</div><div><b>EROSIONAL</b><ol><li><b>cirque</b></li><li><b>horns and ridges</b></li><li><b>u-shaped valleys</b> &gt; Tarn lakes &gt;also &gt; Fjords, submerged glacial valley inlet of sea</li></ol><div><br></div></div><div><b>depositional FEATURES</b><ol><li>Glacical till &gt; debris dropped</li><li>outwash plains</li><li>morains</li><li>eskers</li><li>drumlins &gt; stoss and tail</li></ol></div><div><br></div><div><b>Alps</b> &gt;highest peak Mattenhorn</div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div></div></article>
            </div>`}

            ]