var miscellaneous=[

    { title: "Syllabus Plan ",content:`<input id="chapter" placeholder="Chapter" value="Syllabus">
            <input id="subtitle" class="subtitle" placeholder="Chapter Name" value="Plan">
            <div id="editor" class="editor" contenteditable="true" style="background-size: 100% 32px;">
                <article><br></article><article><article>#History</article><article>Sources</article><article><ol class="custom-list"><li><span style="background-color: initial; caret-color: red;">spectrum</span></li><li>bipin chandra notes</li><li>themes 12th class</li></ol></article><article><br></article><article>Logs</article><article><ol><li>Enter log here</li></ol><br></article><article><br></article><article>#Geography</article><article>6th - 12th ncerts<br></article><article>videos<br></article><article><br></article><article><br></article><article><br></article><article>#Environment</article><article>shankar ias book<br></article><article>pt365 videos&nbsp;<br></article><article><br></article><article>#Economics</article><article>mrunal videos<br></article><article>11th and 12th ncert<br></article><article><br></article><article>#Polity</article><article>laxmikanth chapterwise<br></article><article>COI Articles<br></article><article><br></article><article><br></article><article><b>#Science</b></article><article><b>Sources</b><ol class="custom-list"><li><span style="background-color: initial; caret-color: red;">ncert 6th-10th prefer tamil board books</span></li></ol><div><br></div><div><b>Logs</b></div><div><ol><li>tamil board &gt; class 9th &gt; chapter 14 acids, salts, bases</li><li>ncert &gt; class 10th &gt; chapter 2 acids and bases</li><li>tamil board &gt; class 9th &gt; chapter 16 animal and plant kingdom<span style="white-space: pre;">	</span></li></ol><br></div></article><article><br></article><article>#Current Affairs</article><article>gktoday quiz and monthly<br></article><article>only ias daily<br></article><article>trivial facts</article><article>defense exercises<br></article><article>awards etc<br></article><article><br></article><article><br></article><article><br></article><article><br></article><article><br></article><article><br></article></article>
            </div>`}
    

]