let organisations =
[

{ title: "WEF IO ",content:`<input id="chapter" placeholder="Chapter" value="WEF">
            <input id="subtitle" class="subtitle" placeholder="Chapter Name" value="IO">
            <div id="editor" class="editor" contenteditable="true" style="background-size: 100% 32px;">
                <article><span style="background-color: initial; caret-color: red;">World Economic Forum &gt; <b>1971</b> &gt; not for profit organisation &gt; a public private cooperation</span></article><article><span style="background-color: initial; caret-color: red;"><b>HQ</b>: Geneva, Switzerland</span></article><article><b>Founder</b>: Klaus Schwab</article><article><span style="background-color: initial; caret-color: red;"><b>Mission</b>: improving state of world</span></article><article><span style="background-color: initial; caret-color: red;"><b>Vision</b> &gt; shaping future of Economic, social, industry systems</span></article><article><span style="background-color: initial; caret-color: red;"><b>Values</b> &gt; independence, impartiality, integrity</span></article><article><span style="background-color: initial; caret-color: red;"><b>Area of Work</b> &gt; not specific &gt; all governance, environment, sustainable development</span></article><article><span style="background-color: initial; caret-color: red;"><br></span></article><article><span style="background-color: initial; caret-color: red;"><br></span></article><article><b>Reports</b></article><article><b><span style="background-color: initial; caret-color: red;">The Global Risks Report 2020 &gt;&nbsp;</span>An Unsettled
World</b><span style="background-color: initial; caret-color: red;"><ol class="custom-list"><li>top risk &gt; extreme weather &gt; climatic action failure</li></ol><div><br></div><div><b>Global Gender Gap Report 2020</b></div><div><ol class="custom-list"><li><span style="background-color: initial; caret-color: red;">Top: Iceland &gt; Norway &gt; Finland</span></li><li><span style="background-color: initial; caret-color: red;"><b>112 rank &gt; India </b>&gt; score &gt; 0.668</span></li><li><span style="background-color: initial; caret-color: red;">Score 0-1</span></li></ol></div><div><br></div><div><br></div><div><br></div></span></article><article><br></article>
            </div>`}


]